## Univariate Imputation

In [3]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

In [4]:


data = {
    'Name':["Rohan","Krish","Bob","Sohit","Neha","Mayank"],
    'Age':[24,np.nan,34,24,np.nan,35],
    'Score':[85,90,np.nan,88,92,96],
    'Attendance':[100,90,80,np.nan,87,92]
}

df = pd.DataFrame(data)
df

,Name,Age,Score,Attendance
0,Rohan,24.0,85.0,100.0
1,Krish,NaN,90.0,90.0
2,Bob,34.0,NaN,80.0
3,Sohit,24.0,88.0,NaN
4,Neha,NaN,92.0,87.0
5,Mayank,35.0,96.0,92.0


## Mean imputer

In [5]:
mean_imputer = SimpleImputer(strategy='mean')

df_mean_imputed = mean_imputer.fit_transform(df[['Age','Score']])

In [6]:
print(df_mean_imputed)

[[24.   85.  ]
 [29.25 90.  ]
 [34.   90.2 ]
 [24.   88.  ]
 [29.25 92.  ]
 [35.   96.  ]]


In [7]:
df['Age'].mean()

29.25

## Median Imputer

In [8]:
median_imputer = SimpleImputer(strategy='median')

df_meadian_imputed = median_imputer.fit_transform(df[['Age','Score']])

In [9]:
pd.DataFrame(df_meadian_imputed,columns=['Age','Score'])

,Age,Score
0,24.0,85.0
1,29.0,90.0
2,34.0,90.0
3,24.0,88.0
4,29.0,92.0
5,35.0,96.0


## most_frequent Imputer

In [10]:
most_frequent_imputed = SimpleImputer(strategy='most_frequent')

df_most_frequent_imputed = most_frequent_imputed.fit_transform(df[['Age','Attendance']])

In [11]:
df_most_frequent_imputed

array([[ 24., 100.],
       [ 24.,  90.],
       [ 34.,  80.],
       [ 24.,  80.],
       [ 24.,  87.],
       [ 35.,  92.]])

In [12]:
df['Notes'] = [np.nan,'Good',np.nan,'Average',np.nan,'Average']

In [13]:
most_frequent_imputer_txt = SimpleImputer(strategy='most_frequent')

most_frequent_imputed_text = most_frequent_imputer_txt.fit_transform(df[['Score','Notes']])

In [14]:
most_frequent_imputed_text

array([[85.0, 'Average'],
       [90.0, 'Good'],
       [85.0, 'Average'],
       [88.0, 'Average'],
       [92.0, 'Average'],
       [96.0, 'Average']], dtype=object)

## Constant Imputer

In [15]:
constant_imputer = SimpleImputer(strategy='constant',fill_value = -1)

df_constant_imputed = constant_imputer.fit_transform(df[['Score','Attendance']])

In [16]:
df_constant_imputed

array([[ 85., 100.],
       [ 90.,  90.],
       [ -1.,  80.],
       [ 88.,  -1.],
       [ 92.,  87.],
       [ 96.,  92.]])

In [18]:
constant_imputer_text = SimpleImputer(strategy='constant',fill_value="Not found")

df_constant_imputed_text = constant_imputer_text.fit_transform(df[['Notes']])

In [19]:
df_constant_imputed_text

array([['Not found'],
       ['Good'],
       ['Not found'],
       ['Average'],
       ['Not found'],
       ['Average']], dtype=object)