<h1>Numpy</h2>

Numpy is made of with Numerical + python.

In [ ]:
pip install numpy

In [1]:
import numpy as np

Creating array

In [2]:
lst = [34,23,52,5]
arr = np.array([2,3,4,5,6])
print(lst)
print(type(lst))
print(arr)
print(type(arr))

[34, 23, 52, 5]
<class 'list'>
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
matrix = np.array([
    [2,3,4],
    [4,5,2],
    [8,0,3]])

In [4]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [5]:
matrix.ndim

2

In [6]:
arr.ndim

1

In [9]:
zero_arr= np.zeros((3,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
zero_matrix = np.zeros((2,3,3))
zero_matrix

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
np.ones(5) #2d,3d,4d...

array([1., 1., 1., 1., 1.])

In [18]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [21]:
np.arange(3)

array([0, 1, 2])

In [24]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [27]:
rating = np.random.rand(10)

In [28]:
rating

array([0.46357182, 0.10049695, 0.40040418, 0.47210491, 0.24127968,
       0.27365581, 0.28373854, 0.23016702, 0.7878672 , 0.52038753])

In [9]:
np.random.randint(12,30,100)

array([19, 18, 28, 19, 16, 15, 22, 19, 13, 13, 13, 18, 25, 19, 18, 21, 21,
       13, 23, 13, 29, 24, 24, 14, 18, 18, 23, 12, 19, 15, 27, 22, 18, 14,
       29, 18, 26, 14, 12, 13, 26, 27, 24, 29, 12, 17, 22, 25, 13, 19, 12,
       16, 16, 12, 19, 25, 19, 18, 21, 18, 14, 29, 20, 14, 12, 22, 19, 12,
       22, 28, 17, 20, 27, 28, 20, 27, 25, 18, 21, 29, 15, 26, 28, 15, 14,
       25, 24, 21, 22, 29, 16, 12, 14, 17, 18, 23, 20, 22, 28, 27])

In [31]:
np.random.choice(["Furniture","Toys","Appliances"],20)

array(['Appliances', 'Furniture', 'Furniture', 'Furniture', 'Toys',
       'Furniture', 'Furniture', 'Furniture', 'Appliances', 'Appliances',
       'Appliances', 'Appliances', 'Furniture', 'Appliances',
       'Appliances', 'Appliances', 'Appliances', 'Toys', 'Furniture',
       'Appliances'], dtype='<U10')

In [32]:
matrix.shape

(3, 3)

In [58]:
matrix.dtype

dtype('int64')

In [34]:
arr.size

5

In [35]:
matrix.size

9

In [37]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [36]:
matrix[2][1]

0

In [38]:
arr[1]

3

In [40]:
matrix[0:2,0:2]

array([[2, 3],
       [4, 5]])

In [84]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [85]:
arr

array([2, 3, 4, 5, 6])

In [86]:
matrix*3

array([[ 6,  9, 12],
       [12, 15,  6],
       [24,  0,  9]])

In [87]:
arr * 2

array([ 4,  6,  8, 10, 12])

In [88]:
matrix + 23

array([[25, 26, 27],
       [27, 28, 25],
       [31, 23, 26]])

In [91]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [41]:
ar = np.array([2,3,1])
ar

array([2, 3, 1])

In [42]:
matrix*ar

array([[ 4,  9,  4],
       [ 8, 15,  2],
       [16,  0,  3]])

In [94]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [92]:
cl = np.array([[2],
               [3],
               [4]])

In [93]:
matrix * cl

array([[ 4,  6,  8],
       [12, 15,  6],
       [32,  0, 12]])

In [ ]:
matrix.flatten() # it converts any n dimenstion array in 1 Dimension

array([2, 3, 4, 4, 5, 2, 8, 0, 3])

In [97]:
np.sum(matrix)

np.int64(31)

In [98]:
np.sum(arr)

np.int64(20)

In [99]:
np.min(matrix)

np.int64(0)

In [100]:
np.max(matrix)

np.int64(8)

In [101]:
np.var(matrix)

np.float64(4.469135802469136)

In [102]:
np.std(matrix)

np.float64(2.1140330656044943)

In [103]:
np.mean(matrix)

np.float64(3.4444444444444446)

In [104]:
np.median(matrix)

np.float64(3.0)

In [105]:
np.argmax(matrix)

np.int64(6)

In [106]:
np.argmin(matrix)

np.int64(7)

In [115]:
np.sort(arr)

array([2, 3, 4, 5, 6])

In [46]:
np.sort(matrix,axis=1,kind='quicksort',)

array([[2, 3, 4],
       [2, 4, 5],
       [0, 3, 8]])

In [117]:
arr

array([2, 3, 4, 5, 6])

In [49]:
np.where(arr>3,True,False).sum()

3

In [50]:
np.where(matrix==3,True,False).sum()

2

In [51]:
arr = np.array([1,3,3,2,4,5,5,4,4,4,2])

In [52]:
np.bincount(arr)

array([0, 1, 2, 2, 4, 2])

In [134]:
np.unique(arr)

array([1, 2, 3, 4, 5])