<h1>Numpy</h2>

Numpy is made of with Numerical + python.

In [ ]:
pip install numpy

In [2]:
import numpy as np

Creating array

In [2]:
lst = [34,23,52,5]
arr = np.array([2,3,4,5,6])
print(lst)
print(type(lst))
print(arr)
print(type(arr))

[34, 23, 52, 5]
<class 'list'>
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
matrix = np.array([
    [2,3,4],
    [4,5,2],
    [8,0,3]])

In [4]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [6]:
matrix.ndim

2

In [7]:
arr.ndim

1

In [5]:
zero_arr= np.zeros((2,2))
zero_arr

array([[0., 0.],
       [0., 0.]])

In [15]:
zero_matrix = np.zeros((2,3,2,3))
zero_matrix

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
np.ones(2) #2d,3d,4d...

array([1., 1.])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.arange(3)

array([0, 1, 2])

In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
rating = np.random.rand(10)

In [8]:
rating

array([0.37515272, 0.67529005, 0.30445236, 0.58387454, 0.51414606,
       0.66567067, 0.21713048, 0.01315679, 0.60280254, 0.32814964])

In [9]:
np.random.randint(12,30,100)

array([19, 18, 28, 19, 16, 15, 22, 19, 13, 13, 13, 18, 25, 19, 18, 21, 21,
       13, 23, 13, 29, 24, 24, 14, 18, 18, 23, 12, 19, 15, 27, 22, 18, 14,
       29, 18, 26, 14, 12, 13, 26, 27, 24, 29, 12, 17, 22, 25, 13, 19, 12,
       16, 16, 12, 19, 25, 19, 18, 21, 18, 14, 29, 20, 14, 12, 22, 19, 12,
       22, 28, 17, 20, 27, 28, 20, 27, 25, 18, 21, 29, 15, 26, 28, 15, 14,
       25, 24, 21, 22, 29, 16, 12, 14, 17, 18, 23, 20, 22, 28, 27])

In [56]:
np.random.choice(["Furniture","Toys","Appliances"],20)

array(['Toys', 'Furniture', 'Toys', 'Appliances', 'Appliances', 'Toys',
       'Furniture', 'Toys', 'Furniture', 'Toys', 'Appliances', 'Toys',
       'Furniture', 'Appliances', 'Toys', 'Appliances', 'Appliances',
       'Furniture', 'Appliances', 'Toys'], dtype='<U10')

In [57]:
matrix.shape

(3, 3)

In [58]:
matrix.dtype

dtype('int64')

In [59]:
arr.size

5

In [60]:
matrix.size

9

In [61]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [73]:
matrix[2][1]

np.int64(0)

In [74]:
arr[1]

np.int64(3)

In [83]:
matrix[0:2,0:2]

array([[2, 3],
       [4, 5]])

In [84]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [85]:
arr

array([2, 3, 4, 5, 6])

In [86]:
matrix*3

array([[ 6,  9, 12],
       [12, 15,  6],
       [24,  0,  9]])

In [87]:
arr * 2

array([ 4,  6,  8, 10, 12])

In [88]:
matrix + 23

array([[25, 26, 27],
       [27, 28, 25],
       [31, 23, 26]])

In [91]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [89]:
ar = np.array([2,3,1])
ar

array([2, 3, 1])

In [90]:
matrix*ar

array([[ 4,  9,  4],
       [ 8, 15,  2],
       [16,  0,  3]])

In [94]:
matrix

array([[2, 3, 4],
       [4, 5, 2],
       [8, 0, 3]])

In [92]:
cl = np.array([[2],
               [3],
               [4]])

In [93]:
matrix * cl

array([[ 4,  6,  8],
       [12, 15,  6],
       [32,  0, 12]])

In [ ]:
matrix.flatten() # it converts any n dimenstion array in 1 Dimension

array([2, 3, 4, 4, 5, 2, 8, 0, 3])

In [97]:
np.sum(matrix)

np.int64(31)

In [98]:
np.sum(arr)

np.int64(20)

In [99]:
np.min(matrix)

np.int64(0)

In [100]:
np.max(matrix)

np.int64(8)

In [101]:
np.var(matrix)

np.float64(4.469135802469136)

In [102]:
np.std(matrix)

np.float64(2.1140330656044943)

In [103]:
np.mean(matrix)

np.float64(3.4444444444444446)

In [104]:
np.median(matrix)

np.float64(3.0)

In [105]:
np.argmax(matrix)

np.int64(6)

In [106]:
np.argmin(matrix)

np.int64(7)

In [115]:
np.sort(arr)

array([2, 3, 4, 5, 6])

In [ ]:
np.sort(matrix,axis=1,kind='quicksort',)

array([[2, 3, 4],
       [2, 4, 5],
       [0, 3, 8]])

In [117]:
arr

array([2, 3, 4, 5, 6])

In [123]:
np.where(arr>4,True,False).sum()

np.int64(2)

In [127]:
np.where(matrix==3,True,False).sum()

np.int64(2)

In [132]:
arr = np.array([1,3,3,2,4,5,5,4,4,4,2])

In [133]:
np.bincount(arr)

array([0, 1, 2, 2, 4, 2])

In [134]:
np.unique(arr)

array([1, 2, 3, 4, 5])